/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    videos: Video;
    reels: Reel;
    'rate-card-packages': RateCardPackage;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'rate-card-packages': RateCardPackagesSelect<false> | RateCardPackagesSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    work: Work;
    about: About;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    work: WorkSelect<false> | WorkSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can sign in to this admin panel. Add an account to give someone access; delete one to take it away.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images used across the site, including reel posters. Uploaded automatically when you attach an image elsewhere — you rarely need to add anything here by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Reel video files (MP4 only, up to 50MB each). Usually uploaded straight from a reel rather than added here directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Everything in the gallery on your Work page. Each reel needs a video file and a poster image — the still shown before it plays. Reels are grouped on the site by category, and 'order' decides which comes first inside a group: lower numbers appear earlier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  /**
   * The hook / review headline.
   */
  title: string;
  /**
   * The app or business being reviewed.
   */
  subject: string;
  category:
    | 'Money & fintech'
    | 'AI & creator tools'
    | 'Commerce & brands'
    | 'Ed-tech'
    | 'Health & fitness'
    | 'Real estate'
    | 'SaaS & B2B';
  kind: 'app' | 'business';
  /**
   * Upload a file here and it belongs to this reel alone. Leave it empty and the card shows just the poster until you add one.
   */
  video?: (number | null) | Video;
  /**
   * 9:16 still shown before the video plays.
   */
  poster: number | Media;
  /**
   * Optional link to the original Instagram / YouTube post.
   */
  href?: string | null;
  /**
   * Lower numbers appear first within the category.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The pricing tiles on your Connect page. Each package shows a name, a one-line description, what's included, and a starting price. 'Order' controls left-to-right position: lower numbers appear first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card-packages".
 */
export interface RateCardPackage {
  id: number;
  name: string;
  blurb: string;
  deliverables: {
    item: string;
    id?: string | null;
  }[];
  /**
   * Shown verbatim, e.g. "from ₹25,000".
   */
  priceFrom: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  reels?: {
    /**
     * Allow clients to find reels.
     */
    find?: boolean | null;
    /**
     * Allow clients to create reels.
     */
    create?: boolean | null;
    /**
     * Allow clients to update reels.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete reels.
     */
    delete?: boolean | null;
  };
  rateCardPackages?: {
    /**
     * Allow clients to find rate-card-packages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create rate-card-packages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update rate-card-packages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete rate-card-packages.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  videos?: {
    /**
     * Allow clients to find videos.
     */
    find?: boolean | null;
    /**
     * Allow clients to create videos.
     */
    create?: boolean | null;
    /**
     * Allow clients to update videos.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete videos.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null)
    | ({
        relationTo: 'rate-card-packages';
        value: number | RateCardPackage;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  category?: T;
  kind?: T;
  video?: T;
  poster?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-card-packages_select".
 */
export interface RateCardPackagesSelect<T extends boolean = true> {
  name?: T;
  blurb?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  priceFrom?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  reels?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  rateCardPackages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  videos?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * All the writing on your Work page — the headline at the top, the section intros, the case-study placeholder, the process steps, and the closing call to action. The reels themselves live under 'Reels'.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * The handwritten line above the headline.
     */
    script: string;
    headline: string;
    intro: string;
    /**
     * The small pill with the pulsing dot.
     */
    availability: string;
  };
  gallery: {
    eyebrow: string;
    heading: string;
    /**
     * Shown in place of the gallery when there are no reels.
     */
    emptyState: string;
  };
  caseStudy: {
    eyebrow: string;
    heading: string;
    intro: string;
    /**
     * The small pill inside the dashed box.
     */
    badge: string;
    coverTitle: string;
    /**
     * Numbered automatically in the order listed here.
     */
    items?:
      | {
          label: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  process: {
    eyebrow: string;
    heading: string;
    /**
     * Numbered automatically in the order listed here.
     */
    steps?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    script: string;
    heading: string;
    /**
     * The filled button. Always links to the Connect page.
     */
    primaryLabel: string;
    /**
     * The outlined button. Always links to the About page.
     */
    secondaryLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every piece of writing on your About page, section by section. Edit any field and the live site updates as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    availability: string;
    eyebrow: string;
    headline: string;
    intro: string;
    bio?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    signature: string;
  };
  whoIAm: {
    eyebrow: string;
    heading: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    education?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    qualifications?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    languages?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  values: {
    eyebrow: string;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  bring: {
    eyebrow: string;
    /**
     * Mentions how many reasons there are, so update it if you add or remove items below.
     */
    heading: string;
    items?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  quote: {
    text: string;
    attribution: string;
  };
  /**
   * Headings for the scrolling logo wall. The logos themselves are set in code.
   */
  radar: {
    eyebrow: string;
    heading: string;
  };
  cta: {
    script: string;
    heading: string;
    /**
     * The filled button. Always links to the Connect page.
     */
    primaryLabel: string;
    /**
     * The outlined button. Always links to the Work page.
     */
    secondaryLabel: string;
  };
  /**
   * Tiny flourishes: the sideways label running up the left edge, and the words circling the rotating wax seal.
   */
  props: {
    sideLabel: string;
    /**
     * Wraps a circle, so keep it short or it will overlap.
     */
    sealText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How people reach you from the Connect page: your email, your Cal.com booking link, your social links, the rate-card PDF, and the ready-made email starters visitors can pick from.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  /**
   * Cal.com "<username>/<event>", e.g. "varsheni/intro".
   */
  calLink: string;
  instagram: string;
  youtube: string;
  /**
   * Path or URL to the rate-card PDF, e.g. "/rate-card.pdf".
   */
  rateCardPdf: string;
  responseTime: string;
  /**
   * Pre-written mailto: starters for the Connect page carousel.
   */
  mailTemplates?:
    | {
        key: string;
        label: string;
        subject: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        script?: T;
        headline?: T;
        intro?: T;
        availability?: T;
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        emptyState?: T;
      };
  caseStudy?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        badge?: T;
        coverTitle?: T;
        items?:
          | T
          | {
              label?: T;
              body?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        script?: T;
        heading?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        availability?: T;
        eyebrow?: T;
        headline?: T;
        intro?: T;
        bio?:
          | T
          | {
              text?: T;
              id?: T;
            };
        signature?: T;
      };
  whoIAm?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        education?:
          | T
          | {
              item?: T;
              id?: T;
            };
        qualifications?:
          | T
          | {
              item?: T;
              id?: T;
            };
        languages?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        eyebrow?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  bring?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  radar?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  cta?:
    | T
    | {
        script?: T;
        heading?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  props?:
    | T
    | {
        sideLabel?: T;
        sealText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  calLink?: T;
  instagram?: T;
  youtube?: T;
  rateCardPdf?: T;
  responseTime?: T;
  mailTemplates?:
    | T
    | {
        key?: T;
        label?: T;
        subject?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}